# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: windows-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd D:\a\Fifteen\Fifteen
    - run: npm install -g create-react-app
    - run: dir
    - run: npm start
    - run: cd..
    - run: npm create-react-app Fifteen
    - run: npm start
    - run: npm publish --access public
    - run: npm build
      env:
        CI: true
