name: windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Fifteen
    runs-on: self-hosted

    steps:
      - name: Init
        uses: actions/checkout@v1
      - run: npm ci

      - name: Start
        uses: actions-runner/checkout@v2
      - run: ./config.cmd --url https://github.com/GiaconBruno/Fifteen --token ANLKIXK2Z4AC4BJGGUZSBTS6RUN4Q
      - run: ./run.cmd

      - name: Node.js Start
        uses: actions-runner/checkout@v2
      - run: npm install create-react-app
      - run: npm run-script start
